
---
################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:

    SeriesOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
                - *OrdererOrg2
        Consortiums:
            SeriesConsortium:
                Organizations:
                    - *netflix
                    - *hbo
                    - *pordede

    serieschannel:
        Consortium: SeriesConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *netflix
                - *hbo
                - *pordede


################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    # SampleOrg defines an MSP using the sampleconfig.  It should never be used
    # in production but may be used as a template for other definitions
    - &OrdererOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: OrdererOrg

        # ID to load the MSP definition as
        ID: OrdererMSP

        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: crypto-config/ordererOrganizations/myapp.com/msp
     # SampleOrg defines an MSP using the sampleconfig.  It should never be used
    # in production but may be used as a template for other definitions
    - &OrdererOrg2
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: OrdererOrg2

        # ID to load the MSP definition as
        ID: Orderer2MSP

        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: crypto-config/ordererOrganizations/myapp2.com/msp

    - &netflix
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: netflixMSP

        # ID to load the MSP definition as
        ID: netflixMSP

        MSPDir: crypto-config/peerOrganizations/netflix.myapp.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.netflix.myapp.com
              Port: 7051
    - &pordede
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: pordedeMSP

        # ID to load the MSP definition as
        ID: pordedeMSP

        MSPDir: crypto-config/peerOrganizations/pordede.myapp2.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.pordede.myapp2.com
              Port: 7051

    - &hbo
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: hboMSP

        # ID to load the MSP definition as
        ID: hboMSP

        MSPDir: crypto-config/peerOrganizations/hbo.myapp.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.hbo.myapp.com
              Port: 7051



################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    # Available types are "solo" and "kafka"
    OrdererType: kafka

    Addresses:
        - orderer.myapp.com:7050

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 2s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 98 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    Kafka:
        # Brokers: A list of Kafka brokers to which the orderer connects
        # NOTE: Use IP:port notation
        Brokers:
            - 172.16.239.4:9092
            - 172.16.239.5:9093
            - 172.16.239.6:9094

    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:
