version: '2'

services:
  caFca:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-fca
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.fca.regulatory.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/5e915e49e679db8866d22b25148b183bf8bf16ae5af6ae3294f0be2edb6d26a7_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.fca.regulatory.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/5e915e49e679db8866d22b25148b183bf8bf16ae5af6ae3294f0be2edb6d26a7_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/fca.regulatory.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerFca

  caBank1:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-bank1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.bank1.regulatory.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/a0d3c95b3ce9330709b69d130e8a80efb8a25e56ce137cf597e1c061a8d64009_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.bank1.regulatory.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/a0d3c95b3ce9330709b69d130e8a80efb8a25e56ce137cf597e1c061a8d64009_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/bank1.regulatory.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerBank1

  orderer.regulatory.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.regulatory.com
    container_name: orderer.regulatory.com

  peer0.fca.regulatory.com:
    container_name: peer0.fca.regulatory.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.fca.regulatory.com

  peer0.bank1.regulatory.com:
    container_name: peer0.bank1.regulatory.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.bank1.regulatory.com

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.fca.regulatory.com:7051
      - CORE_PEER_LOCALMSPID=fcaMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/fca.regulatory.com/peers/peer0.fca.regulatory.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/fca.regulatory.com/peers/peer0.fca.regulatory.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/fca.regulatory.com/peers/peer0.fca.regulatory.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/fca.regulatory.com/users/Admin@fca.regulatory.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    #command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME}; sleep $TIMEOUT'
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincodes/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.regulatory.com
      - peer0.fca.regulatory.com
      - peer0.bank1.regulatory.com
