# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.myapp.com:
    container_name: orderer.myapp.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/myapp.com/orderers/orderer.myapp.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/myapp.com/orderers/orderer.myapp.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050

  peer0.netflix.myapp.com:
    container_name: peer0.netflix.myapp.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.netflix.myapp.com
      - CORE_PEER_ADDRESS=peer0.netflix.myapp.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.netflix.myapp.com:7051
      - CORE_PEER_LOCALMSPID=netflixMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/netflix.myapp.com/peers/peer0.netflix.myapp.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/netflix.myapp.com/peers/peer0.netflix.myapp.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053

  peer0.hbo.myapp.com:
    container_name: peer0.hbo.myapp.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.hbo.myapp.com
      - CORE_PEER_ADDRESS=peer0.hbo.myapp.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hbo.myapp.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.hbo.myapp.com:7051
      - CORE_PEER_LOCALMSPID=hboMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/hbo.myapp.com/peers/peer0.hbo.myapp.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/hbo.myapp.com/peers/peer0.hbo.myapp.com/tls:/etc/hyperledger/fabric/tls
